version: '3.9'

services:
  math-service:
    build: ./math_py
    ports:  
      - 5001:5001
  
  string-service:
    build: ./string_rust
    ports:  
      - 5000:5000
 
  gateway-service:
    build: ./gateway
    ports:  
      - 5002:5002